spring:
  application:
    name: sping-data-jpa
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
  datasourcemysql1:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    datasource:
      username: mysql1-user
      password: password
      url: jdbc:mysql://localhost:3306/datasourcemysql1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 20
      connection-timeout: 30000
      schema: public
  datasourcemysql2:
    enabled: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: mysql2-user
      password: password
      url: jdbc:mysql://localhost:3306/datasourcemysql2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 20
      connection-timeout: 30000
      schema: public
  datasourcemysql3:
    enabled: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: mysql1-user
      password: password
      url: jdbc:mysql://localhost:3306/datasourcemysql3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 20
      connection-timeout: 30000
      schema: public
  h2:
    console:
      path: /h2-console
      enabled: true
      # if not provided -> database hash and passaword to connect are in the Console logs
  liquibase:
    change-log: liquibase-changelog-master.yaml
database:
  name: bookdb
  port: 3306
  server: 127.0.0.1
logging:
  level:
    # Show bind values
    org.hibernate.orm.jdbc.bind: INFO
