spring:
  application:
    name: sping-data-jpa
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: bookuser
    password: password
    url: jdbc:mysql://${database.server}:${database.port}/${database.name}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 20
      connection-timeout: 30000
  sql:
    init:
      mode: always
  liquibase:
    change-log: liquibase-changelog-master.yaml
    user: bookadmin
    password: password
database:
  name: bookdb
  port: 3306
  server: 127.0.0.1
logging:
  level:
    # Show bind values
    org.hibernate.orm.jdbc.bind: trace
